"""Studio /dapi/ paths — same registry as the official studio CLI."""

AUTH_ME = "/dapi/auth/me/"
AUTH_PROFILE = "/dapi/auth/profile/"

USERS = "/dapi/users/"
USER_DETAIL = "/dapi/users/{id}/"

TEAMS = "/dapi/teams/"
TEAM_DETAIL = "/dapi/teams/{id}/"
TEAM_MEMBERS = "/dapi/teams/{id}/members/"
TEAM_MEMBER_DETAIL = "/dapi/teams/{id}/members/{user_id}/"
TEAM_INVITATIONS = "/dapi/teams/{id}/invitations/"

PLATFORM_CATALOG = "/dapi/platforms/catalog/"
PLATFORM_CATALOG_DETAIL = "/dapi/platforms/catalog/{id}/"
PLATFORM_CONFIGS = "/dapi/platforms/configs/"
PLATFORM_CONFIG_DETAIL = "/dapi/platforms/configs/{id}/"
PLATFORM_CONNECT = "/dapi/platforms/connect/"
PLATFORM_DISCONNECT = "/dapi/platforms/disconnect/"

KB_LIST = "/dapi/knowledge-bases/"
KB_DETAIL = "/dapi/knowledge-bases/{id}/"
KB_DOCUMENTS = "/dapi/knowledge-bases/{id}/documents/"
KB_DOCUMENT_DETAIL = "/dapi/knowledge-bases/{id}/documents/{doc_id}/"
KB_DOMAINS = "/dapi/knowledge-bases/{id}/domains/"
KB_DOMAIN_DETAIL = "/dapi/knowledge-bases/{id}/domains/{domain_id}/"
KB_DOMAIN_CRAWL = "/dapi/knowledge-bases/{id}/domains/{domain_id}/crawl/"
KB_STATS = "/dapi/knowledge-bases/{id}/stats/"
KB_SEARCH = "/dapi/knowledge-bases/{id}/search/"

AGENT_KB_STATS = "/dapi/agents/{agent_id}/kb/stats/"
AGENT_KB_SEARCH = "/dapi/agents/{agent_id}/kb/search/"
AGENT_KB_TEST = "/dapi/agents/{agent_id}/kb/test/"
AGENT_KB_ATTACHMENTS = "/dapi/agents/{agent_id}/knowledge-bases/"
AGENT_KB_ATTACHMENT_DETAIL = "/dapi/agents/{agent_id}/knowledge-bases/{attachment_id}/"
AGENT_KB_AVAILABLE = "/dapi/agents/{agent_id}/knowledge-bases/available/"
AGENT_KB_DOCUMENTS = "/dapi/agents/{agent_id}/kb/documents/"
AGENT_KB_DOMAINS = "/dapi/agents/{agent_id}/kb/domains/"
AGENT_KB_DOMAIN_DETAIL = "/dapi/agents/{agent_id}/kb/domains/{domain_id}/"
AGENT_KB_DOMAIN_CRAWL = "/dapi/agents/{agent_id}/kb/domains/{domain_id}/crawl/"

AGENTS = "/dapi/agents/"
AGENT_DETAIL = "/dapi/agents/{id}/"
AGENT_PREVIEW = "/dapi/agents/{id}/preview/"

MCP_SERVERS = "/dapi/mcp/servers/"
MCP_SERVER_DETAIL = "/dapi/mcp/servers/{id}/"
MCP_CONNECTIONS = "/dapi/mcp/connections/"
MCP_CONNECTION_DETAIL = "/dapi/mcp/connections/{id}/"
MCP_OAUTH_INITIATE = "/dapi/mcp/connections/{id}/oauth/initiate/"

HTTP_API_TOOLS = "/dapi/http-api/tools/"
HTTP_API_TOOL_DETAIL = "/dapi/http-api/tools/{id}/"
HTTP_API_CONNECTIONS = "/dapi/http-api/connections/"
HTTP_API_CONNECTION_DETAIL = "/dapi/http-api/connections/{id}/"
HTTP_API_CONNECTION_EXECUTE = "/dapi/http-api/connections/{id}/execute/"
HTTP_API_OAUTH_INITIATE = "/dapi/http-api/connections/{id}/oauth/initiate/"

LLM_PROVIDERS = "/dapi/llm/providers/"
LLM_PROVIDER_DETAIL = "/dapi/llm/providers/{id}/"
LLM_PROVIDER_MODELS = "/dapi/llm/providers/{id}/models/"
LLM_PROVIDER_CONFIGS = "/dapi/llm/configs/"
LLM_PROVIDER_CONFIG_DETAIL = "/dapi/llm/configs/{id}/"
